[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.virtualenv"]

[phases.install]
cmds = [
  "python -m venv venv",
  "source venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "source venv/bin/activate && python manage.py collectstatic --no-input",
  "source venv/bin/activate && python manage.py migrate --noinput"
]

[start]
cmd = "source venv/bin/activate && chmod +x start.sh && ./start.sh" 