[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = [
  "python manage.py collectstatic --no-input",
  "python manage.py migrate --noinput"
]

[start]
cmd = "chmod +x start.sh && ./start.sh" 