# Generated by Django 5.2.4 on 2025-07-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_receiver",
            field=models.BooleanField(default=False),
        ),
    ]
